/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { FileItem } from "./FileItem";

// Mock数据
export const MEMO_DATA: FileItem[] = [
  new FileItem('test1.png'),
  new FileItem('test2.ppt'),
  new FileItem('test3.doc'),
  new FileItem('test4.xls'),
  new FileItem('test5.xls'),
  new FileItem('test6.xls'),
  new FileItem('test7.doc'),
  new FileItem('test8.ppt'),
  new FileItem('test9.doc'),
  new FileItem('test5.png')
];