/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {
  // 动画总时长10s
  static readonly ANIMATION_DURATION: number = 10000;
  // 延时时间1s
  static readonly DELAY_TIME: number = 1000;
  // 间隔距离
  static readonly BLANK_SPACE: number = 50;
  // 间隔距离
  static readonly ANGLE: number = 180;
  // 默认文本字体颜色
  static readonly DEFAULT_FONT_COLOR: string = '#000';
  // 默认文本字体大小
  static readonly DEFAULT_FONT_SIZE: number = 16;
  // 默认跑马灯动画时间
  static readonly DEFAULT_ANIMATION_DURATION: number = 500;
  // 默认滚动轴宽度
  static readonly DEFAULT_SCROLL_WIDTH: string = '25%';
}
