/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export { CustomAnimationTab } from './src/main/ets/utils/CustomAnimationTab'
export { AnimationAttribute } from './src/main/ets/model/AnimationAttribute'
export { CustomAnimationTabController } from './src/main/ets/model/CustomAniamtionTabController'
export { IndicatorBarAttribute } from './src/main/ets/model/IndicatorBarAttribute'
export { TabBarAttribute } from './src/main/ets/model/TabBarAttribute'
export { TabBarItemInterface } from './src/main/ets/model/TabBarItemInterface'
export { TabInfo } from './src/main/ets/model/TabInfo'
export { BaseInterface } from './src/main/ets/model/BaseInterface'
export { CustomAnimationTabView } from './src/main/ets/view/CustomAnimationTabView'
export * from './src/main/ets/generated/RouterBuilder';