/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { PlatformTypeEnum,ThirdLevelCategory } from '../model/CategoricalDataType'

export const SELF_TEST: ThirdLevelCategory[] = [
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.Modifier'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'Modifier',
      abilityName: 'ModifierAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.VideoPlayDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'VideoPlayDemo',
      abilityName: 'VideoPlayDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.FileApi'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'FileApi',
      abilityName: 'FileApiAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.RDBDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'RDBDemo',
      abilityName: 'RDBDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.UDMFDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'UDMFDemo',
      abilityName: 'UDMFDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.PreferencesDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'PreferencesDemo',
      abilityName: 'PreferencesDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.RequestDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'RequestDemo',
      abilityName: 'RequestDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.Drawing'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'Drawing',
      abilityName: 'DrawingAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.Window'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'Window',
      abilityName: 'WindowAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.GeoLocationManagerDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'GeoLocationManagerDemo',
      abilityName: 'GeoLocationManagerDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.VibrationBasicDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'VibrationBasicDemo',
      abilityName: 'VibrationBasicDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.VibratorCustomHapticDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'VibratorCustomHapticDemo',
      abilityName: 'VibratorCustomHapticDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.VibratorJsSamplesDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'VibratorJsSamplesDemo',
      abilityName: 'VibratorJsSamplesDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.TaskPoolDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'TaskPoolDemo',
      abilityName: 'TaskPoolDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.CollectionsDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'CollectionsDemo',
      abilityName: 'CollectionsDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.FastBufferDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'FastBufferDemo',
      abilityName: 'FastBufferDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.UtilsDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'UtilsDemo',
      abilityName: 'UtilsDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.ImageDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'ImageDemo',
      abilityName: 'ImageDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.VidoDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'VidoDemo',
      abilityName: 'VidoDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.I18nDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'I18nDemo',
      abilityName: 'I18nDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.HighContrastDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'HighContrastDemo',
      abilityName: 'HighContrastDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.HyperlinkDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'HyperlinkDemo',
      abilityName: 'HyperlinkDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.GraphicsTextDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'GraphicsTextDemo',
      abilityName: 'GraphicsTextDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.WebSocketDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'WebSocketDemo',
      abilityName: 'WebSocketDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.distributedKVStoreDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'distributedKVStoreDemo',
      abilityName: 'DistributedKVStoreDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
  {
    image: $r('app.media.ic_unselect_component'),
    title: $r('app.string.EnableHapticFeedbackDemo'),
    want: {
      bundleName: 'com.example.enjoyarkuix',
      moduleName: 'EnableHapticFeedbackDemo',
      abilityName: 'EnableHapticFeedbackDemoAbility',
    },
    platform: PlatformTypeEnum.SUPPORT_BOTH
  },
]