// import router from '@ohos.router';
//
// @Entry
// @Component
// struct Index {
//
//   build() {
//     RelativeContainer() {
//       Column() {
//         Button('EntityRecognizer')
//           .fontSize(16)
//           .margin({ bottom: 20 })
//           .width('80%')
//           .height(45)
//           .backgroundColor('#007dff')
//           .borderRadius(22)
//           .onClick(() => {
//             router.pushUrl({url:"pages/EntityRecognizer"})
//           })
//         Button('i18n')
//           .fontSize(16)
//           .margin({ bottom: 20 })
//           .width('80%')
//           .height(45)
//           .backgroundColor('#007dff')
//           .borderRadius(22)
//           .onClick(() => {
//             router.pushUrl({url:"pages/i18n"})
//           })
//         Button('SimpleDateTimeFormat')
//           .fontSize(16)
//           .margin({ bottom: 20 })
//           .width('80%')
//           .height(45)
//           .backgroundColor('#007dff')
//           .borderRadius(22)
//           .onClick(() => {
//             router.pushUrl({url:"pages/SimpleDateTimeFormat"})
//           })
//         Button('SimpleNumberFormat')
//           .fontSize(16)
//           .margin({ bottom: 20 })
//           .width('80%')
//           .height(45)
//           .backgroundColor('#007dff')
//           .borderRadius(22)
//           .onClick(() => {
//             router.pushUrl({url:"pages/SimpleNumberFormat"})
//           })
//         Button('StyledNumberFormat')
//           .fontSize(16)
//           .margin({ bottom: 20 })
//           .width('80%')
//           .height(45)
//           .backgroundColor('#007dff')
//           .borderRadius(22)
//           .onClick(() => {
//             router.pushUrl({url:"pages/StyledNumberFormat"})
//           })
//       }
//       .height('100%')
//       .width('100%')
//     }.height('100%').padding(12)
//   }
// }
