/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 视频播放控制器。用于控制视频的播放暂停及播放进度。
 */
export class VideoPlayController {
  // 播放接口
  play = () => {
  };
  // 暂停接口
  pause = () => {
  };
  // 播放进度接口
  seek = (currentTime: number) => {
  };
}
