/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  // 默认水印内容1
  static readonly TEXT_CONTENT1: string = '水印水印';
  // 默认水印字体大小1
  static readonly FONT_SIZE1: string = '16vp';
  // 默认水印字体颜色1
  static readonly FONT_COLOR1: string = '#10000000';
  // 默认水印内容2
  static readonly TEXT_CONTENT2: string = '追逐繁星的太阳';
  // 默认水印字体大小1
  static readonly FONT_SIZE2: string = '32vp';
  // 默认水印字体颜色1
  static readonly FONT_COLOR2: string = '#FFF';
  // 默认设置水印文本绘制中的文本对齐方式
  static readonly TEXT_ALIGN: CanvasTextAlign = 'center';
  // 默认设置水印文本绘制中的水平对齐方式
  static readonly TEXT_BASE_LINE: CanvasTextBaseline = 'bottom';
  // 默认设置水印文本绘制阴影时的模糊级别
  static readonly TEXT_SHADOW_BLUE: number = 20;
  // 默认设置水印文本绘制阴影时的阴影颜色
  static readonly TEXT_SHADOW_COLOR: string = '#F3F3F3';
  // 视图100%
  static readonly COMPONENT_VIEW_FULL:string = '100%';
}