/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ExampleDataModel, SearchDataModel } from '../model/searchModel'

export const exampleData: Array<ExampleDataModel> = [
  new ExampleDataModel("精品好礼"),
  new ExampleDataModel("品牌手机"),
  new ExampleDataModel("节日大优惠"),
  new ExampleDataModel("学生背包"),
  new ExampleDataModel("零食"),
  new ExampleDataModel("手机壳"),
  new ExampleDataModel("毛绒玩具"),
  new ExampleDataModel("行李箱")
]

export const searchData: Array<SearchDataModel> = [
  new SearchDataModel("XX"),
  new SearchDataModel("商品"),
  new SearchDataModel("XX手机"),
  new SearchDataModel("微商"),
  new SearchDataModel("5G手机"),
  new SearchDataModel("成品好衣"),
  new SearchDataModel("视频"),
  new SearchDataModel("XX品牌手机"),
  new SearchDataModel("精品手机"),
  new SearchDataModel("羽绒服"),
  new SearchDataModel("图片"),
  new SearchDataModel("精品好礼"),
  new SearchDataModel("品牌手机"),
  new SearchDataModel("节日大优惠"),
  new SearchDataModel("双肩包"),
  new SearchDataModel("零食"),
  new SearchDataModel("手机壳"),
  new SearchDataModel("毛绒玩具"),
  new SearchDataModel("行李箱")
]