/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 自定义属性
 */
export class CustomAnimationTabConfigure {
  // 背景条最大偏移距离(单位: px)
  static readonly INDICATOR_MAX_LEFT = 90;
  // 背景条宽度扩展比例
  static readonly DEFAULT_INDICATOR_EXPAND = 1;
  // 页签宽度
  static readonly LIST_ITEM_WIDTH = 100;
  // 背景条高度
  static readonly TABBAR_HEIGHT = 70;
  // 背景条宽度
  static readonly INDICATOR_WIDTH = 100;
  // tab标题
  static readonly DEFAULT_BASE_TAB = "全部";
  // tab标题
  static readonly DEFAULT_DYEFFECT_TAB = "动效";
  // tab标题
  static readonly DEFAULT_NATIVE_TAB = "Native";
  // tab标题
  static readonly DEFAULT_OTHER_TAB = "其它";
  // tab标题
  static readonly DEFAULT_THIRTYPARTY_TAB = "三方库";
  // tab标题
  static readonly DEFAULT_UI_TAB = "UI布局";
}