/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Constants {
  static readonly COLUMN_SPACE: number = 8; // column内容间距
  static readonly TRIANGLE_WIDTH: number = 10; // 信息窗口三角宽度
  static readonly TRIANGLE_HEIGHT: number = 8; // 信息窗口三角高度
  static readonly DEFAULT_ANIMATION_DURATION: number = 100; // 默认动画时长
  static readonly DEFAULT_LOCATION_TIME_INTERVAL: number = 3; // 监听位置变化的时间间隔，单位为秒
}