/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Model } from '../model/Model';

export const LIST_DATA: Array<Model> = [
  new Model(0, $r("app.media.status_bar_animation_picture0"), "粉花与蝴蝶的共舞", "粉花盛开绚丽多彩，蝴蝶翩翩起舞其间。",
    66, 23, true, 66, false, 2),
  new Model(1, $r("app.media.status_bar_animation_picture1"), "忙碌的蜜蜂与紫色花朵",
    "一只勤劳的蜜蜂正忙碌地停留在紫色花朵上采集花蜜。", 64, 88,
    false, 81, true, 2),
  new Model(2, $r("app.media.status_bar_animation_picture2"), "白色花朵群的优雅",
    "中心是一群优雅的白色花朵，在柔和的光线中绽放，背景略显模糊。", 72, 92,
    true, 76, false, 1),
  new Model(3, $r("app.media.status_bar_animation_picture3"), "紫色花朵的特写镜头",
    "一朵优雅的紫色花朵在暗绿色背景中绽放，特写镜头捕捉其细节之美。", 41, 15,
    true, 29, true, 2),
  new Model(4, $r("app.media.status_bar_animation_picture4"), "鲜艳的橙色蘑菇",
    "鲜艳的橙色蘑菇在暗色背景下显得格外突出，形态独特。", 90, 15,
    false, 99, false, 1),
  new Model(5, $r("app.media.status_bar_animation_picture5"), "郁郁葱葱的森林风光",
    "一片郁郁葱葱的森林，阳光透过树叶洒落，营造出宁静和谐的氛围。", 66, 15,
    true, 11, false, 2),
  new Model(6, $r("app.media.status_bar_animation_picture6"), "自然光下的粉红色花朵",
    "一朵粉红色的花在自然光下显得格外娇嫩，花瓣细腻柔美。", 54, 15,
    true, 33, false, 2),
  new Model(7, $r("app.media.status_bar_animation_picture7"), "蒲公英绒毛的特写",
    "两朵蒲公英的绒毛清晰可见，形状似伞，随风轻轻摇曳。", 44, 87,
    true, 88, true, 2),
  new Model(8, $r("app.media.status_bar_animation_picture8"), "深紫色花朵的神秘之美",
    "深紫色的花朵在暗色调背景中更显神秘，花瓣层次分明。", 77, 65,
    true, 94, false, 2),
  new Model(9, $r("app.media.status_bar_animation_picture9"), "黑白蝴蝶的优雅停驻",
    "黑白相间的蝴蝶优雅地停留在绿叶上，翅膀上的图案精致美丽。", 91, 15,
    true, 81, false, 1),
  new Model(10, $r("app.media.status_bar_animation_picture10"), "诱人草莓的甜蜜滋味",
    "新鲜的草莓，鲜红诱人，看起来非常美味可口。", 36, 15,
    false, 26, true, 2),
  new Model(11, $r("app.media.status_bar_animation_picture11"), "微风吹拂下的金色麦浪",
    "麦田在风中摇曳，形成一片金黄的波浪，宛如流动的黄金。", 83, 81,
    false, 87, false, 1),
  new Model(12, $r("app.media.status_bar_animation_picture12"), "粉色樱花的浪漫盛放",
    "粉色的樱花在树枝上绽放，美丽动人，仿佛置身于粉色的梦幻世界。", 37, 44,
    true, 66, true, 2),
  new Model(13, $r("app.media.status_bar_animation_picture13"), "夜幕下植物园的奇幻色彩",
    "植物园里的植物在灯光的照射下呈现出五彩斑斓的颜色，营造出神秘而迷人的夜景。", 54, 15,
    true, 32, false, 2)
];