/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  // toast停留时间
  static readonly TOAST_DURATION: number = 2000;
  // 动画过渡时长
  static readonly ANIMATION_DURATION = 200;
  // 分割线高度
  static readonly DIVIDER_HEIGHT: number = 2;
  // 组件间距
  static readonly SPACE_GAP_24 = 24;

  static readonly WIDTH_FULL = '100%';
  static readonly HEIGHT_FULL = '100%';


  // 商品价格及信息
  static readonly PRICE_MOUNT: string = '1款，共1件 ';
  static readonly PRICE_AMOUNT: string = '合计: ';
  static readonly PRICE_ICON: string = '¥';
  static readonly PRICE_FIRST: string = '7699';
  static readonly PRICE_LAST: string = '.00';
  static readonly REDUCE: string = '共减 ¥ 599.00';
  static readonly SUBMIT_ORDER: string = '提交订单';
  static readonly PRICE_DETAIL: string = '价格明细';
  static readonly PRICE_AMOUNT1: string = '商品总价 ';
  static readonly PRICE_AMOUNT2: string = '共1件宝贝';
  static readonly PRICE_AMOUNT3: string = '¥ 7699.00';
  static readonly PRICE_REDUCE1: string = '共减';
  static readonly PRICE_REDUCE2: string = '- ¥ 599.00';
  static readonly PRICE_ORIGIN1: string = '官方立减';
  static readonly PRICE_ORIGIN2: string = '- ¥ 499.00';
  static readonly PRICE_SHOP1: string = '店铺优惠';
  static readonly PRICE_SHOP2: string = '- ¥ 100.00';
  static readonly PRICE_ALL1: string = '合计';
  static readonly PRICE_ALL2: string = '¥ 7100.00';
  static readonly SHOP_NAME: string = 'XXX官方旗舰店';
  static readonly GOODS_NAME: string = 'XX手机PRO MAX 2025';
  static readonly TYPE_NAME: string = '512g 白色';
  static readonly PRICE_ORIGIN: string = '¥7699';
  static readonly PRICE_LOWER: string = '券后 ¥ 7100';
  static readonly GOODS_NUMBER: string = '1';

  // 收货地址信息
  static readonly NAME_BAR: string = '收货人名字';
  static readonly PHONE_BAR: string = '电话';
  static readonly ADDRESS_BAR: string = '所在地区';
  static readonly DETAIL_ADDRESS_BAR: string = '详细地址';
  static readonly USE_ADDRESS: string = '使用地址';
  static readonly ADD_ADDRESS: string = '新增地址';
  static readonly USE_SUCCESS: string = '使用成功';
  static readonly NAME_EMPTY: string = '收货人名字不能为空！';
  static readonly PHONE_EMPTY: string = '电话不能为空!';
  static readonly ADDRESS_EMPTY: string = '所在地区不能为空！';
  static readonly DETAIL_ADDRESS_EMPTY: string = '详细地址不能为空！';




  static readonly NAME: string = '李小明';
  static readonly PHONE: string = '13012345678';
  static readonly ADDRESS: string = '中国江苏省南京市雨花台区雨花街道';
  static readonly DETAIL_ADDRESS: string = '玉兰路98号';

}